-- MySQL Script generated by MySQL Workbench
-- dijous, 3 de maig de 2018, 14:28:14 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema epawTwitter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `epawTwitter` ;

-- -----------------------------------------------------
-- Schema epawTwitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epawTwitter` DEFAULT CHARACTER SET utf8 ;
USE `epawTwitter` ;

-- -----------------------------------------------------
-- Table `epawTwitter`.`userconsoles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epawTwitter`.`userconsoles` ;

CREATE TABLE IF NOT EXISTS `epawTwitter`.`userconsoles` (
  `userconsolesid` INT NOT NULL AUTO_INCREMENT,
  `ps1` BIT NULL,
  `ps2` BIT NULL,
  `ps3` BIT NULL,
  `ps4` BIT NULL COMMENT '		',
  `3ds` BIT NULL,
  `wii` BIT NULL,
  `switch` BIT NULL,
  `xbox` BIT NULL,
  `xbox360` BIT NULL,
  `xboxone` BIT NULL,
  `pc` BIT NULL,
  `mobile` BIT NULL,
  `others` VARCHAR(45) NULL,
  PRIMARY KEY (`userconsolesid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epawTwitter`.`usergamegenres`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epawTwitter`.`usergamegenres` ;

CREATE TABLE IF NOT EXISTS `epawTwitter`.`usergamegenres` (
  `usergamegenresid` INT NOT NULL AUTO_INCREMENT,
  `action` BIT NULL,
  `actionadventure` BIT NULL,
  `adventure` BIT NULL,
  `roleplaying` BIT NULL,
  `simulation` BIT NULL,
  `strategy` BIT NULL,
  `sports` BIT NULL,
  `other` BIT NULL,
  PRIMARY KEY (`usergamegenresid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `epawTwitter`.`registeredusers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epawTwitter`.`registeredusers` ;

CREATE TABLE IF NOT EXISTS `epawTwitter`.`registeredusers` (
  `userid` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `dob` DATE NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `description` VARCHAR(200) NULL,
  `gender` INT NOT NULL,
  `youtubeid` VARCHAR(45) NULL,
  `twitchid` VARCHAR(45) NULL,
  `userconsoles_userconsolesid` INT NOT NULL,
  `usergamegenres_usergamegenresid` INT NOT NULL,
  PRIMARY KEY (`userid`, `userconsoles_userconsolesid`, `usergamegenres_usergamegenresid`),
  INDEX `fk_registeredusers_userconsoles_idx` (`userconsoles_userconsolesid` ASC),
  INDEX `fk_registeredusers_usergamegenres1_idx` (`usergamegenres_usergamegenresid` ASC),
  CONSTRAINT `fk_registeredusers_userconsoles`
    FOREIGN KEY (`userconsoles_userconsolesid`)
    REFERENCES `epawTwitter`.`userconsoles` (`userconsolesid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_registeredusers_usergamegenres1`
    FOREIGN KEY (`usergamegenres_usergamegenresid`)
    REFERENCES `epawTwitter`.`usergamegenres` (`usergamegenresid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
