-- MySQL Script generated by MySQL Workbench
-- 05/03/18 16:21:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema epawTwitter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `epawTwitter` ;

-- -----------------------------------------------------
-- Schema epawTwitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epawTwitter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `epawTwitter` ;

-- -----------------------------------------------------
-- Table `epawTwitter`.`registeredusers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `epawTwitter`.`registeredusers` ;

CREATE TABLE IF NOT EXISTS `epawTwitter`.`registeredusers` (
  `user` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `gender` VARCHAR(59) NULL,
  `youtubeChannelID` VARCHAR(45) NULL,
  `twitchChannelID` VARCHAR(45) NULL,
  `gameGenres` VARCHAR(255) NULL,
  `userConsoles` VARCHAR(255) NULL,
  `mail` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`user`, `mail`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
