-- MySQL Script generated by MySQL Workbench
-- 05/03/18 16:21:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema epawTwitter
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `epawTwitter` ;

-- -----------------------------------------------------
-- Schema epawTwitter
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `epawTwitter` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `epawTwitter` ;

-- -----------------------------------------------------
-- Drop Tables
-- -----------------------------------------------------

DROP TABLE IF EXISTS `epawTwitter`.`Users`;
DROP TABLE IF EXISTS `epawTwitter`.`Tweets`;
DROP TABLE IF EXISTS `epawTwitter`.`Feedback`;
DROP TABLE IF EXISTS `epawTwitter`.`Relationship`;

-- -----------------------------------------------------
-- Table `epawTwitter`.`Users`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `epawTwitter`.`Users` (
  `user` VARCHAR(255) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `birthDate` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `gender` VARCHAR(59) NULL,
  `youtubeChannelID` VARCHAR(45) NULL,
  `twitchChannelID` VARCHAR(45) NULL,
  `gameGenres` VARCHAR(255) NULL,
  `userConsoles` VARCHAR(255) NULL,
  `mail` VARCHAR(80) NOT NULL,
  `isAdmin` BIT DEFAULT 0 NOT NULL,
  PRIMARY KEY (`user`, `mail`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `epawTwitter`.`Tweets`
-- -----------------------------------------------------
  
CREATE TABLE IF NOT EXISTS `epawTwitter`.`Tweets` (
  `tweetID` INTEGER NOT NULL AUTO_INCREMENT,
  `author` VARCHAR(255) NOT NULL,
  `likes` INTEGER DEFAULT 0,
  `message` VARCHAR(255) NOT NULL,
  `publishDate` TIMESTAMP NOT NULL,
  PRIMARY KEY (`tweetID`),
  CONSTRAINT FK_Tweets_author FOREIGN KEY (`author`) REFERENCES Users(`user`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `epawTwitter`.`Feedback`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `epawTwitter`.`Feedback` (
  `tweet1` INTEGER NOT NULL,
  `tweet2` INTEGER NOT NULL,
  PRIMARY KEY (`tweet1`, `tweet2`),
  CONSTRAINT FK_Feedback_tweet1 FOREIGN KEY (`tweet1`) REFERENCES Tweets(`tweetID`),
  CONSTRAINT FK_Feedback_tweet2 FOREIGN KEY (`tweet2`) REFERENCES Tweets(`tweetID`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `epawTwitter`.`Relationship`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `epawTwitter`.`Relationship` (
  `userA` VARCHAR(255) NOT NULL,
  `userB` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`userA`, `userB`),
  CONSTRAINT FK_Relationship_userA FOREIGN KEY (`userA`) REFERENCES Users(`user`),
  CONSTRAINT FK_Relationship_userB FOREIGN KEY (`userB`) REFERENCES Users(`user`)
) 
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


INSERT INTO Users (user, name, surname, birthDate, password, gender, mail)
	VALUES ('test', 'test', 'test', '1992-12-12', 'testtest', 'male', 'test@test.com');

INSERT INTO Users (user, name, surname, birthDate, password, gender, mail)
	VALUES ('test2', 'test', 'test', '1992-12-12', 'testtest', 'male', 'test2@test.com');
    
INSERT INTO Users (user, name, surname, birthDate, password, gender, mail)
	VALUES ('test3', 'test', 'test', '1992-12-12', 'testtest', 'male', 'test3@test.com');

INSERT INTO Relationship (userA, userB) VALUES ('test', 'test2');
INSERT INTO Relationship (userA, userB) VALUES ('test2', 'test');

INSERT INTO Tweets (author, message, publishDate) VALUES ('test', 'Test of tweet', sysdate());
INSERT INTO Tweets (author, message, publishDate) VALUES ('test', 'Genaral Utils is working?', sysdate());
INSERT INTO Tweets (author, message, publishDate) VALUES ('test', 'It looks like yes', sysdate());

INSERT INTO Tweets (author, message, publishDate) VALUES ('test2', 'it still working?', sysdate());
